# Set R_LIBS_USER to a path specific to rocker/rstudio to avoid conflicts with personal libraries from any R installation in the host environment
r-libs-user=R/4.5
# Prevent R session from timeout
session-timeout-minutes=0

