---
title: "RNA-seq analysis"
author: "Aleksandr Bykov"
date: '2025-01-30'
output:
  html_document:
    self_contained: false
---

```{r Load libraries, include=FALSE}
#knitr::opts_chunk$set(include = FALSE)

# Set up the environment ####
# Importing only key functions that are actually used - not to polute namespace!
import::from(openxlsx, createWorkbook, addWorksheet, writeData, saveWorkbook)
import::from(
  .from = here::here("~/workspace/neuroblastoma/resources/UtilityScriptsRNA-seq.R"),
  "filterDatasets",
  "generatePCA",
  "generateEnsemblAnnotation",
  "generateResults",
  "meanExprsPerGroup",
  "plotVolcano",
  .character_only = TRUE
) # used for filtering

library(stringr)
library(org.Hs.eg.db)
library(fgsea)
library(ggplot2)
library(DESeq2)

plot(hist(1:10))
```

```{r Load essentials assets}
# load gene sets
gs_hallmark <- hypeR::msigdb_gsets(species = "Homo sapiens", category = c("H"), clean = TRUE)
gs_C2_kegg <- hypeR::msigdb_gsets(species = "Homo sapiens", category = c("C2"), subcategory = "CP:KEGG", clean = TRUE)
gs_C2_reactome <- hypeR::msigdb_gsets(species = "Homo sapiens", category = c("C2"), subcategory = "CP:REACTOME", clean = TRUE)
gs_C5_GOBP <- hypeR::msigdb_gsets(species = "Homo sapiens", category = c("C5"), subcategory = "GO:BP", clean = TRUE)
gs_C5_GOCC <- hypeR::msigdb_gsets(species = "Homo sapiens", category = c("C5"), subcategory = "GO:CC", clean = TRUE)
gs_C5_GOMF <- hypeR::msigdb_gsets(species = "Homo sapiens", category = c("C5"), subcategory = "GO:MF", clean = TRUE)
gs_C6_onco <- hypeR::msigdb_gsets(species = "Homo sapiens", category = c("C6"), clean = TRUE)
gs_wang_hippo <- list(wang_hippo_set = c("CCN1", "CCN2", "AMOTL2", "ANKRD1", "IGFBP3", "F3", "FJX1", "NUAK2", "LATS2", "CRIM1", "GADD45A","TGFB2", "PTPN14", "NT5E", "FOXF2", "AXL", "DOCK5", "ASAP1", "RBMS3", "MYOF", "ARHGEF17", "CCDC80"))

# loading BioMart
options(timeout = 30000)
mart <- biomaRt::useMart(
  biomart = "ENSEMBL_MART_ENSEMBL", 
  dataset = "hsapiens_gene_ensembl",
  host = "https://www.ensembl.org")
  
# Set up the parameters
param_list <- list(
  abs_filt_samples = 2,
  padj_cutoff = 0.05,
  log2FC_cutoff = 1,
  var_expl_needed = 0.6
)
deg_dir <- "~/workspace/neuroblastoma/results/RNA-seq/"

plot(hist(20:30))

```

This module loads RNA-seq count table and produces PCA plot, including all samples, even the STA_NB_6 that is removed later on

```{r Load RNA-seq data and produce PCA plot with ALL samples included, echo=FALSE}
# Analysis of the RNA-seq data ####
# Loading the DESeq2 file and annotation file that was used during the pre-processing of the data
path_folder_rna_seq_data <- "~/workspace/neuroblastoma/data/RNAseq"
rnaseq_dds <- readRDS(file.path(path_folder_rna_seq_data, "rnaseq_deseq_global_deseq_data_set.rds"))
design(rnaseq_dds) <- as.formula("~ cell_line + cell_type")
annotationData <- read.table(
  file = file.path(path_folder_rna_seq_data, "rnaseq_deseq_global_annotation_gene.tsv"),
  sep = "\t",
  header = TRUE
)
# This is necessary to rename columns so that extraction of the data works correctly
colnames(annotationData)[c(5, 7)] <- c("ensembl_id", "gene_symbol")

# make PCA with ALL samples
# Filtering lowly expressed genes
tmp_rnaseq_dds_filt <- filterDatasets(rnaseq_dds,
  abs_filt = TRUE,
  abs_filt_samples = param_list$abs_filt_samples
)
# Estimate size factors and running DESEQ2
tmp_rnaseq_dds_filt <- DESeq2::estimateSizeFactors(tmp_rnaseq_dds_filt)
tmp_rnaseq_dds_filt <- DESeq2::DESeq(tmp_rnaseq_dds_filt)
# Stabilize variance
tmp_vsd <- DESeq2::vst(tmp_rnaseq_dds_filt, blind = TRUE) # blind = TRUE for QC

# generate PCA plots
tmp_pca_deg <- generatePCA(
  transf_object = tmp_vsd,
  cond_interest_varPart = c("cell_type", "cell_line"),
  color_variable = "cell_type",
  shape_variable = "cell_line",
  ntop_genes = 1000
) +
  scale_color_manual(values = c("navy", "firebrick3")) +
  scale_shape_manual(values = c(16, 7, 17, 15, 3)) +
  ggtitle("RNA-seq Original dataset")
# ggsave(
#   filename = paste0(deg_dir, "PCA_full_dataset.png"),
#   plot = tmp_pca_deg,
#   width = 20, height = 20, units = "cm"
# )
plot(tmp_pca_deg)
```