---
title: "RNA-seq Overexpression Analysis - Improved Version"
author: "Aleksandr Bykov (Enhanced by Claude Code)"
date: '`r Sys.Date()`'
output:
  html_document: 
    toc: true
    toc_float: true
    code_folding: hide
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 10,
  fig.height = 8,
  dpi = 300
)

set.seed(42)
analysis_start_time <- Sys.time()
message("Starting RNA-seq overexpression analysis at: ", analysis_start_time)
```

## Configuration and Setup

```{r configuration}
config <- list(
  filtering = list(
    abs_filt_samples = 2,
    min_count_threshold = 10
  ),
  statistical = list(
    padj_cutoff = 0.05,
    log2FC_cutoff = 0.37,
    var_expl_needed = 0.6
  ),
  visualization = list(
    ntop_genes_pca = 1000,
    plot_width = 20,
    plot_height = 20,
    plot_units = "cm",
    top_pathways_show = 20
  ),
  biomart = list(
    host = "http://www.ensembl.org",
    dataset = "hsapiens_gene_ensembl",
    version = "Ensembl Genes 109"
  )
)

PATHS <- list(
  data_dir = here::here("data", "RNAseq"),
  results_dir = here::here("results", "RNA-seq_OE"),
  resources_dir = here::here("resources"),
  cache_dir = here::here("cache")
)

print("Configuration loaded successfully")
```

```{r load_libraries}
# Create cache directory if needed
if (!dir.exists("/home/rstudio/.cache/R/ExperimentHub")) {
  dir.create("/home/rstudio/.cache/R/ExperimentHub", recursive = TRUE)
}

suppressPackageStartupMessages({
  # Core analysis packages
  library(DESeq2)
  library(stringr)
  library(org.Hs.eg.db)
  
  # Enrichment analysis
  library(fgsea)
  library(GSVA)
  library(xcore)
  library(ExperimentHub)
  library(xcoredata)
  
  # Visualization
  library(ggplot2)
  library(pheatmap)
  
  # Data manipulation
  library(dplyr)
  library(tidyr)
  library(readr)
  
  # File operations
  library(openxlsx)
  library(here)
  
  # Utility functions from existing scripts
  import::from(
    .from = here::here("resources/UtilityScriptsRNA-seq.R"),
    "filterDatasets", "generatePCA", "generateEnsemblAnnotation", 
    "generateResults", "meanExprsPerGroup", "plotVolcano", "generatePCA_repel", ".dots_plot_fixed",
    .character_only = TRUE
  )
})

environment(.dots_plot_fixed) <- asNamespace("hypeR")
assignInNamespace(".dots_plot", .dots_plot_fixed, ns = "hypeR")

print("Libraries loaded successfully")
```

```{r setup_environment}
if(!dir.exists(PATHS$results_dir)) dir.create(PATHS$results_dir, recursive = TRUE)
if(!dir.exists(PATHS$cache_dir)) dir.create(PATHS$cache_dir, recursive = TRUE)

# Load annotation data
annotation_data <- read.table(
  file = file.path(PATHS$data_dir, "rnaseq_deseq_global_annotation_gene.tsv"),
  sep = "\t",
  header = TRUE
)
# Standardize column names
colnames(annotation_data)[c(5, 7)] <- c("ensembl_id", "gene_symbol")

print("Environment setup completed")
```
```{r Load the counts data, echo = FALSE}
#loading the new DESeq2 file
load(file.path(PATHS$data_dir, "deseq2.dds.RData"))
rnaseq_dds <- dds[,
                  c(
                    "CLB_Ma_ADR_rep1",
                    "CLB_Ma_ADR_rep2",
                    "CLB_Ma_MES_rep1",
                    "CLB_Ma_MES_rep2",
                    "CLBM_A_RNA_S130492",
                    "CLBM_M_RNA_S130495",
                    "SH_A_RNA_S130494",
                    "SH_M_RNA_S130497",
                    "SK_N_SH_ADR_rep1_1",
                    "SK_N_SH_ADR_rep2_1",
                    "SK_N_SH_MES_rep1_1",
                    "SK_N_SH_MES_rep2_1",
                    "CM_OE_EV_RNA_S144621",
                    "CM_OE_WWTR1_RNA_S144623",
                    "CM_OE_YAP1_RNA_S144624",
                    "SH_OE_EV_RNA_S144620",
                    "SH_OE_WWTR1_RNA_S144622",
                    "SH_OE_YAP1_RNA_S144619",
                    "SH_OE_EV_rep1",
                    "SH_OE_YAP1_rep1",
                    "SH_OE_TAZ_rep1",
                    "SH_OE_EV_rep2",
                    "SH_OE_YAP1_rep2",
                    "SH_OE_TAZ_rep2",
                    "CM_OE_EV_rep1",
                    "CM_OE_YAP1_rep1",
                    "CM_OE_TAZ_rep1",
                    "CM_OE_EV_rep2",
                    "CM_OE_YAP1_rep2",
                    "CM_OE_TAZ_rep2"
                  )]

rm(dds)
rnaseq_dds

rnaseq_dds$cell_line <- as.factor(case_when(
  str_detect(colnames(rnaseq_dds), "^(CLB)|^(CM)") ~ "CLBMa",
  str_detect(colnames(rnaseq_dds), "^(SK)|^(SH)") ~ "SK_N_SH",
  .default = colnames(rnaseq_dds)
))

rnaseq_dds$cell_type <- as.factor(case_when(
  str_detect(colnames(rnaseq_dds), "(_ADR_)|(_A_)") ~ "ADR",
  str_detect(colnames(rnaseq_dds), "(_MES_)|(_M_)") ~ "MES",
  .default = "undefined"
))

rnaseq_dds$experiment <- as.factor(case_when(
  colnames(rnaseq_dds) %in% c(
    "CLBM_A_RNA_S130492",
    "CLBM_M_RNA_S130495",
    "SH_A_RNA_S130494",
    "SH_M_RNA_S130497") ~ "batch1",
  
  colnames(rnaseq_dds) %in% c(
    "CM_OE_EV_RNA_S144621",
    "CM_OE_WWTR1_RNA_S144623",
    "CM_OE_YAP1_RNA_S144624",
    "SH_OE_EV_RNA_S144620",
    "SH_OE_WWTR1_RNA_S144622",
    "SH_OE_YAP1_RNA_S144619") ~ "batch2",
  
  colnames(rnaseq_dds) %in% c(
    "CLB_Ma_ADR_rep1",
    "CLB_Ma_ADR_rep2",
    "CLB_Ma_MES_rep1",
    "CLB_Ma_MES_rep2",
    "SK_N_SH_ADR_rep1_1",
    "SK_N_SH_ADR_rep2_1",
    "SK_N_SH_MES_rep1_1",
    "SK_N_SH_MES_rep2_1") ~ "batch3.1",
  
    colnames(rnaseq_dds) %in% c(
      "SH_OE_EV_rep1",
      "SH_OE_YAP1_rep1",
      "SH_OE_TAZ_rep1",
      "SH_OE_EV_rep2",
      "SH_OE_YAP1_rep2",
      "SH_OE_TAZ_rep2",
      "CM_OE_EV_rep1",
      "CM_OE_YAP1_rep1",
      "CM_OE_TAZ_rep1",
      "CM_OE_EV_rep2",
      "CM_OE_YAP1_rep2",
      "CM_OE_TAZ_rep2") ~ "batch3.2",

    .default = colnames(rnaseq_dds)
))

rnaseq_dds$exp_type <- case_when(
  str_detect(colnames(rnaseq_dds), "OE") ~ "OE",
  TRUE ~ "clear_cell_type"
)

rnaseq_dds$OE_factor <- case_when(
  str_detect(colnames(rnaseq_dds), "(WWTR1)|(TAZ)") ~ "WWTR1",
  str_detect(colnames(rnaseq_dds), "YAP1") ~ "YAP1",
  TRUE ~ "EV"
)
  
data.frame(colnames(rnaseq_dds), rnaseq_dds$OE_factor, rnaseq_dds$exp_type, rnaseq_dds$cell_type, rnaseq_dds$cell_line, rnaseq_dds$experiment, rnaseq_dds$sample)




wt_dds <- readRDS("~/workspace/neuroblastoma/data/RNAseq/rnaseq_deseq_global_deseq_data_set.rds")
wt_dds_assay <- as.data.frame(counts(wt_dds))
wt_dds_assay$names_of_rows <- row.names(wt_dds_assay)
rm(wt_dds)

combined_counts <- merge.data.frame(new_dds_assay, 
                                    wt_dds_assay, 
                                    by = "names_of_rows") %>%
  select(-str_subset(colnames(.), "^NB*")) %>%
  rename_with(~ gsub("CLBM", "CM", .x), matches("CLBM"))
row.names(combined_counts) <- combined_counts$names_of_rows
combined_counts <- select(combined_counts, -names_of_rows)

combined_counts_col_data <- data_frame(sample_name = colnames(combined_counts))
combined_counts_col_data$cell_line <- case_when(
  str_detect(combined_counts_col_data$sample_name, "CM") ~ "CM",
  str_detect(combined_counts_col_data$sample_name, "SH") ~ "SH"
)
combined_counts_col_data$exp_type <- case_when(
  str_detect(combined_counts_col_data$sample_name, "(WWTR1)|(YAP1)") ~ "OE",
  TRUE ~ "EV"
)
combined_counts_col_data$OE_factor <- case_when(
  str_detect(combined_counts_col_data$sample_name, "WWTR1") ~ "WWTR1",
  str_detect(combined_counts_col_data$sample_name, "YAP1") ~ "YAP1",
  TRUE ~ "EV"
)
combined_counts_col_data$cell_type <- case_when(
  str_detect(combined_counts_col_data$sample_name, "_A_") ~ "ADRN",
  str_detect(combined_counts_col_data$sample_name, "_M_") ~ "MES",
  TRUE ~ "undefined"
)
combined_counts_col_data$experiment <- case_when(
  str_detect(combined_counts_col_data$sample_name, "OE") ~ "new",
  TRUE ~ "old"
)

dds <- DESeqDataSetFromMatrix(countData = combined_counts, 
                              colData = combined_counts_col_data,
                              design = ~cell_line + exp_type + cell_line:exp_type)
dds <- filterDatasets(dds, 
                      abs_filt = TRUE, 
                      abs_filt_samples = config$filtering$abs_filt_samples)
```

```{r Make PCA plot and do Batch correction}
dds <- DESeq2::estimateSizeFactors(dds)
dds <- DESeq2::DESeq(dds)
#stabilize variance
vsd <- DESeq2::vst(dds, blind = TRUE) # blind = TRUE for QC
#generate PCA plots
pca_deg <- generatePCA_repel(transf_object = vsd, 
                             cond_interest_varPart = c("cell_type","cell_line"), 
                             color_variable = "cell_type", 
                             shape_variable = "cell_line",
                             ntop_genes = 1000) +
  ggtitle("Original dataset") 
plot(pca_deg)

resultsNames(dds)


# Batch correction
transf_batch_NObatch_experiment <- vsd
transf_batch_NObatch_experiment_count <- limma::removeBatchEffect(SummarizedExperiment::assay(transf_batch_NObatch_experiment),
                         transf_batch_NObatch_experiment$experiment)
SummarizedExperiment::assay(transf_batch_NObatch_experiment) <- transf_batch_NObatch_experiment_count
pca_deg_NObatch_experiment <- generatePCA_repel(transf_object = transf_batch_NObatch_experiment, 
                                                cond_interest_varPart = c("cell_type","cell_line"), 
                                                color_variable = "cell_type", 
                                                shape_variable = "cell_line",
                                                ntop_genes = 1000) +
  ggtitle("Original dataset + YAP1/WWTR1 OE") 

#pdf(file = file.path(deg_dir, "pca_wit_corrected_batch_effect.pdf"))
plot(pca_deg_NObatch_experiment)
#dev.off()

```


```{r Perform ssGSEA analysis}
#### ssGSEA analysis
# loading signatures from Groeningen paper
signatures_raw <- readr::read_tsv(file = "/home/rstudio/workspace/neuroblastoma/resources/mes_adr_ncc_noradr_Groeningen_genesets.tsv",
                                  skip_empty_rows = TRUE) # do not add na for empty
sig_list_groeningen <- list(
  #NCC_like = signatures_raw$`NCC-like`[!is.na(signatures_raw$`NCC-like`)],
  #Noradrenergic = signatures_raw$Noradrenergic[!is.na(signatures_raw$Noradrenergic)],
  Mesenchymal  = signatures_raw$Mesenchymal[!is.na(signatures_raw$Mesenchymal)],
  Adrenergic = signatures_raw$Adrenergic[!is.na(signatures_raw$Adrenergic)]
)
lapply(sig_list_groeningen, length)

# load the DE gene list from a previous run and assing genes to ADRN or MES identity 
RNA_SEQ_data <- openxlsx2::read_xlsx("~/workspace/neuroblastoma/results/RNA-seq/cell_type_MES_vs_ADR.xlsx", sheet = 1)
mes_adrn_gene_list <- RNA_SEQ_data %>%
  mutate(Term = if_else(log2FoldChange < 0, "ADRN", "MES"))
sig_list_our_data <- list(
  Aderenergic = mes_adrn_gene_list$gene_symbol[mes_adrn_gene_list$Term == "ADRN"],
  Mesenchymal = mes_adrn_gene_list$gene_symbol[mes_adrn_gene_list$Term == "MES"]
)

# prepare vsd
vsd_counts_matrix <- assay(vsd)
row.names(vsd_counts_matrix) <- annotation_data[, 'gene_symbol'][match(row.names(vsd_counts_matrix), annotation_data[, 'ensembl_id'])]

# Plot the Groeningen terms
ssgsea_mes_adr_cellines <- GSVA::gsva(vsd_counts_matrix,
                                      sig_list_groeningen,
                                      method = c("ssgsea"),
                                      min.sz = 1, max.sz = Inf, 
                                      ssgsea.norm = TRUE, verbose=TRUE, parallel.sz=10)

ssgsea_mes_adr_ncc_noradr_heatmap <- pheatmap::pheatmap(ssgsea_mes_adr_cellines,
                                                        scale = "row",
                                                        #annotation_col = heatmap_col_annot_DTC,
                                                        cluster_rows = TRUE,
                                                        cluster_cols = TRUE,
                                                        color = colorRampPalette(c("navy", "white", "firebrick3"))(50),
                                                        show_colnames = TRUE, 
                                                        main = "SSGSEA Groeningen terms")
#pdf(file = file.path(deg_dir, "ssgsea_mes_adr_ncc_noradr_heatmap_GROEN.pdf"))
ssgsea_mes_adr_ncc_noradr_heatmap
#dev.off()

# Plot terms based on terms defined from RNA-seq profiles obtained from our RNA seq
ssgsea_mes_adr_cellines <- GSVA::gsva(vsd_counts_matrix,
                                      sig_list_our_data,
                                      method=c("ssgsea"),
                                      min.sz=1, max.sz=Inf, 
                                      ssgsea.norm=TRUE, verbose=TRUE, parallel.sz=10)
ssgsea_mes_adr_ncc_noradr_heatmap <- pheatmap::pheatmap(ssgsea_mes_adr_cellines,
                                                                 scale = "row",
                                                                 #annotation_col = heatmap_col_annot_DTC,
                                                                 cluster_rows = TRUE,
                                                                 cluster_cols = TRUE,
                                                                 color = colorRampPalette(c("navy", "white", "firebrick3"))(50),
                                                                 show_colnames = TRUE)
#pdf(file = file.path(deg_dir, "ssgsea_mes_adr_ncc_noradr_heatmap_OUR_RNASEQ.pdf"))
ssgsea_mes_adr_ncc_noradr_heatmap
#dev.off()
```